#!/bin/bash
#SBATCH --job-name=ins
##SBATCH --mail-type=ALL
##SBATCH --mail-user=my-email-address-at-ENS
##SBATCH --time=100:00:00
#SBATCH --ntasks=1
##SBATCJ --cpus-per-task=1

# PLEASE DO NOT TOUCH THE FOLLOWING LINE
source /etc/slurm-llnl/slurm-setup.sh

module purge

# This line is mandatory
cd ${SLURM_RUN_DIR}
# Please comment out the following if you need the subdirectories from    
#     your submission directory
rsync -av --update ${SLURM_SUBMIT_DIR}/ .

#------------------------------------------------------------------------------

# Execute the code
module load gcc
./h4d-mc.x < input-ins > out-ins-YY

# Store the exit status of the parallel job, whether it was successful or not
MYSTATUS=$?

# If the job was not successful, do not copy and erase the data; but you
#     HAVE TO come and control the data, and delete it so soon as possible!!
if [ ${MYSTATUS} -ne 0 ] ; then
  echo "Problem with \"${EXE}\", non-zero exit status: ${MYSTATUS}"
  exit ${MYSTATUS}
fi
